name: Verify style with standard
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2-beta
          with:
            node-version: '12'
        - run: npm ci
        - run: npx semistandard
